### ISSUE TITLE
How do I compile and install this?

### ISSUE THREAD

**Issue by daemonspudguy** [mctofu/musiclib#10]
There's no documentation. How do I build this?

**Comment by mctofu** [comment]
Thanks for asking! Here's the basic steps.

To build the server executable run this from the repo root:
`go build -o musiclib-grpc-server ./cmd/server`

To configure paths to your media files use the `MUSICLIB_ROOT_PATHS` environment variable.
`MUSICLIB_ROOT_PATHS=/path/to/media1,/path/to/media2 ./musiclib-grpc-server`

**Comment by daemonspudguy** [comment]
Thank you!
